"""add telegram to employees

Revision ID: 4711b7b40f06
Revises: 2707f3274c9b
Create Date: 2026-08-06 16:24:05.637293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4711b7b40f06'
down_revision: Union[str, Sequence[str], None] = '2707f3274c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('telegram', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'telegram')
    # ### end Alembic commands ###
